In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('/content/StudentsPerformance.csv')

In [6]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group C,some high school,free/reduced,none,0,17,10
1,female,group B,high school,free/reduced,none,8,24,23
2,female,group B,some high school,free/reduced,none,18,32,28
3,female,group B,some college,standard,none,11,38,32
4,female,group C,some college,free/reduced,none,22,39,33

In [8]:
# Q1 mean, median, and mode
#math score 	reading score 	writing score

means = df[['math score', 'reading score', 'writing score']].mean()
print("\nMean Values\n" ,means)

medians = df[['math score', 'reading score', 'writing score']].median()
print("\nMedian Values\n" ,medians)

modes = df[['math score', 'reading score', 'writing score']].mode()
print("\n Mode Values\n " ,modes)

Mean Values
 math score       66.001
reading score    69.195
writing score    68.119
dtype: float64

Median Values
 math score       66.0
reading score    70.0
writing score    69.0
dtype: float64

 Mode Values
     math score  reading score  writing score
0          65             72             74

In [9]:
# Q2 range, variance, and standard deviation

ranges = df[['math score', 'reading score', 'writing score']].max() - df[['math score', 'reading score', 'writing score']].min()
ranges

math score       100
reading score     83
writing score     90
dtype: int64

In [10]:
variance = df[['math score', 'reading score', 'writing score']].var()
variance

math score       242.411410
reading score    216.279254
writing score    231.842682
dtype: float64

In [11]:
std = df[['math score', 'reading score', 'writing score']].std()
std

math score       15.569567
reading score    14.706436
writing score    15.226381
dtype: float64

In [12]:
# Q3 mean, median, and mode of math scores with different parental education levels


df.groupby('parental level of education')['math score'].mean()

parental level of education
associate's degree    67.977477
bachelor's degree     69.288136
high school           61.821429
master's degree       70.254237
some college          67.128319
some high school      63.134078
Name: math score, dtype: float64

In [13]:
df.groupby('parental level of education')['math score'].median()

parental level of education
associate's degree    67.0
bachelor's degree     68.0
high school           63.0
master's degree       73.0
some college          68.0
some high school      65.0
Name: math score, dtype: float64

In [14]:
df.groupby('parental level of education')['math score'].agg(pd.Series.mode)

parental level of education
associate's degree              65
bachelor's degree     [63, 65, 66]
high school               [57, 66]
master's degree           [79, 81]
some college                    69
some high school          [59, 65]
Name: math score, dtype: object

In [15]:
# Q4 Compare the means of who took the test preparation course versusthose who didn’t.

df.groupby('test preparation course')['math score'].mean()

test preparation course
completed    69.96648
none         63.78972
Name: math score, dtype: float64

In [16]:
# Q 5  interquartile range (IQR)

print("IQR of Math Score")
print(df['math score'].quantile(0.75) - df['math score'].quantile(0.25))
print("IQR of Reading Score")
print(df['math score'].quantile(0.75) - df['reading score'].quantile(0.25))
print("IQR of Writing Score")
print(df['math score'].quantile(0.75) - df['writing score'].quantile(0.25))

IQR of Math Score
20.0
IQR of Reading Score
18.0
IQR of Writing Score
19.0

In [33]:
#Q6 Std of math score on the basis of type of lunch
df.groupby('lunch')['math score'].std()

lunch
free/reduced    15.882442
standard        13.804560
Name: math score, dtype: float64

In [20]:
# Q7 correlation coefficient between math and reading scores, btwn reading and writing scores # Q8

corr = df['math score'].corr(df['reading score'])
print("correlation coefficient between math and reading scores :",corr)
corr = df['reading score'].corr(df['writing score'])
print("correlation coefficient between reading and writing scores :",corr)
#Q8
print("\n Correlation coefficient r > 0 means positive relationship. If the values are closer to 1, that means their correlation strength is very high. \n\
 Therefore here both relation are highly correlated positively. That means both are very closely related. ")

correlation coefficient between math and reading scores : 0.8149368617648359
correlation coefficient between reading and writing scores : 0.953178417390664

 Correlation coefficient r > 0 means positive relationship. If the values are closer to 1, that means their correlation strength is very high.
 Therefore here both relation are highly correlated positively. That means both are very closely related.

In [21]:
# Q9 covariance between math and reading scores.
cov = df['math score'].cov(df['reading score'])
print(cov)

print("Both covariance and correlation are positive relationship,\n\
that means students who score higher in math also probably score higher in reading")

186.59840340340335
Both covariance and correlation are positive relationship,
that means students who score higher in math also probably score higher in reading

In [32]:
# Q10 Z-Test
math_scores = df['math score']

z = (math_scores.mean() - 50) / (math_scores.std(ddof=0) / (len(math_scores) ** 0.5))
float(z)

32.515306479859795

In [31]:
# Q11 T-Test
from scipy import stats

g1 = df[df['lunch']=='free/reduced']['reading score']
g2 = df[df['lunch']=='standard']['reading score']

stats.ttest_ind(g1, g2)

TtestResult(statistic=np.float64(-7.492798943109684), pvalue=np.float64(1.4829967008771313e-13), df=np.float64(998.0))

In [30]:
# Q12 F-Test
prep = df[df['test preparation course']=='completed']['math score']
no_prep = df[df['test preparation course']=='none']['math score']

f = prep.var(ddof=1) / no_prep.var(ddof=1)

from scipy.stats import f as f_dist
p = 1 - f_dist.cdf(f, len(prep)-1, len(no_prep)-1)

float(f), float(p)

(0.8549283313932255, 0.9510755253507813)